### PR TITLE
Add "Essential Go"

### PR DESCRIPTION
**Pull request by kjk**
This might be a good addition (see https://www.reddit.com/r/golang/comments/80ntqx/essential_go_a_free_go_programming_book/)

### CODE REVIEW

**Comment by enocom** [comment]
@kjk Thanks for the PR! I'm wondering if it would be better to split out a separate list of books. It's a stretch to call "Go Bootcamp" a blog post, for example. What do you think?

**Comment by kjk** [comment]
Sounds good to me :)

**Comment by kjk** [comment]
Off the top of my head: no. I imagine there are some.

**Comment by enocom** [comment]
Until we have some critical mass for a separate list of books, I'm inclined to wait on this. 

I've opened an issue and added "Essential Go" there. See #4

**Pull request closed without merging**
