### PR TITLE
Adding Arden Labs Posts

### PR DESCRIPTION
**Pull request by plod**
Thought these were worth adding to your curated list, very good series from Arden Labs on scheduling in Go

### CODE REVIEW

**Comment by enocom** [comment]
Thanks! I've been meaning to add the second part actually (see #78).

I want to keep the list at 200 entries, though, so I'm inclined to take only part 2. That also means we need to find something that can come off the list. Do you have any ideas?

**Comment by plod** [comment]
There's a few scheduler posts, so maybe one of them but which is a tough choice. I'll try and decide which is best candidate but I think Bills newest series is a must have.

**Comment by enocom** [comment]
Maybe Bill's article can replace [The Go netpoller](https://morsmachine.dk/netpoller).

**Comment by enocom** [comment]
Thanks for the suggestion. I've added Bill's post here: d4ebe20cba3fa1218f71a0609e6262af2778dec5.

**Pull request closed without merging**
